### ISSUE TITLE
 encryption support

### ISSUE THREAD

**Issue by aelsharawi** [bitblit/LambdaTranscoderTrigger#1]
Hello

is there anyway to add encryption support in lambda function, so that the user cant download the video?

**Comment by bitblit** [comment]
Sorry I didn't respond to this sooner (I honestly didn't think that anyone was using this so I wasn't tracking it) and I sure hope you already have found an answer to your question!

But, just in case you haven't, the short answer to your question is that whether someone can download the content or not is a function of the configuration of the S3 bucket to which you write it, rather than the encoding process itself.  If you find that someone can download videos (and you don't want them to) you likely need to either change the configuration of the S3 bucket to disallow public access, or you may have Cloudfront configured to expose that bucket as a web site - either way, it will be in their configuration you'll want to look.

Now, if you want to encrypt the output file for other reasons (like you want them to download it, but then pay for it to get a key, etc, then the answers to that are manifold.  From your question I'm guessing that S3 encryption at rest isn't a solution, but python's PyCrypto library probably would work.  You can pip install it.  One word of warning though : PyCrypto relies on natively compiled libraries, so unless you are developing on a Linux box you'll need to do some interesting dancing to get the Linux version of the .SO files into your build or the Lambda version won't work.  If you run into that, this guy can help : https://github.com/Miserlou/lambda-packages

Thanks for looking, and hope this helps!
